# Generated by Django 5.2.1 on 2025-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@vu.edu.in', max_length=100),
            preserve_default=False,
        ),
    ]
