# Generated by Django 5.2.1 on 2025-05-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0002_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@vu.edu.in', max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Student_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_card.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_card.subject')),
            ],
        ),
    ]
